### ISSUE TITLE
请求增加无 JavaScript 模式 适配

### ISSUE THREAD

**Issue by ShuiHuo** [linuxdeepin/docs#1]
1. （亮色/暗色）主题默认使用 CSS 跟随系统。
2. 目录默认展示，根据屏幕宽度可将目录放到开头或侧边。

**Comment by xmuli** [comment]
前端不是很特别擅长，且认为初期应该以内容为主，后续有空闲时间再考虑优化一些 UI 样式；若是有帮助修改样式的人，欢迎直接提 pr。
