### ISSUE TITLE
DTK可以在windows上编译使用吗

### ISSUE THREAD

**Issue by yearnfor** [linuxdeepin/docs#22]
请问DTK可以在windows上编译使用吗，有没有相关参考呢？

**Comment by xmuli** [comment]
以前的 2.2 版本全部可以编译过；5.0 版本之后，上次将 dtkcore 给编译过了，如 dtkwidget 还需要调整，之前有架构师负责移植。记得有一些文章是写过如何在 win 和 mac 编译，遇到过。你也可以探索尝试一番
